feat: update git hooks with actual code

diff --git a/packages/spedue-scripts/git-hooks/pre-commit b/packages/spedue-scripts/git-hooks/pre-commit
--- a/packages/spedue-scripts/git-hooks/pre-commit
+++ b/packages/spedue-scripts/git-hooks/pre-commit
@@ -1,3 +1,53 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash 
 
-echo "I see you're about to commit..."
+echo $GIT_DIR
+
+STAGED=$(git diff --staged --name-only)
+TS_STAGED=$(echo "${STAGED}" | grep -E '\.tsx?$' | tr '\n' ' ')
+JS_STAGED=$(echo "${STAGED}" | grep -E '\.jsx?$' | tr '\n' ' ')
+
+STATUS=0
+
+tsLint() {
+  yarn lint $TS_STAGED
+
+  STATUS=$?
+  if [ $STATUS -ne 0 ]; then 
+    echo "TypeScript linting failed with exit code $STATUS"
+    exit $STATUS
+  fi
+
+  yarn compile
+  
+  STATUS=$?
+  if [ $STATUS -ne 0 ]; then 
+    echo "TypeScript compile failed with exit code $STATUS"
+    exit $STATUS
+  fi
+  
+  git add . 
+}
+
+jsLint() {
+  yarn lint $JS_STAGED
+  
+  STATUS=$?
+  if [ $STATUS -ne 0 ]; then 
+    echo "JavaScript linting failed with exit code $STATUS"
+    exit $STATUS
+  fi
+
+  git add . 
+}
+
+if [[ "$TS_STAGED" != "" ]]; then
+  tsLint
+else
+  echo "Didn't find any staged TypeScript files to lint. Skipping"
+fi
+
+if [[ "$JS_STAGED" != "" ]]; then
+  jsLint
+else
+  echo "Didn't find any staged JavaScript files to lint. Skipping"
+fi
diff --git a/packages/spedue-scripts/git-hooks/pre-push b/packages/spedue-scripts/git-hooks/pre-push
--- a/packages/spedue-scripts/git-hooks/pre-push
+++ b/packages/spedue-scripts/git-hooks/pre-push
@@ -1,3 +1,9 @@
 #!/usr/bin/env bash
 
-echo "Are you sure you want to push?"
+yarn test --noWatch
+
+STATUS=$?
+if [ $STATUS -ne 0 ]; then 
+  echo "Tests failed with exit code $STATUS"
+  exit $STATUS
+fi
